name: Daily Job Alerts

on:
  schedule:
    - cron: '00 4 * * *'   # 09:00 IST
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "✅ Hello! The workflow is running at 9am IST."
